<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Discussion', 'doctrine');

/**
 * BaseDiscussion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $content_id
 * @property enum $content_type
 * @property integer $discussion_id
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method integer    getContentId()     Returns the current record's "content_id" value
 * @method enum       getContentType()   Returns the current record's "content_type" value
 * @method integer    getDiscussionId()  Returns the current record's "discussion_id" value
 * @method Discussion setId()            Sets the current record's "id" value
 * @method Discussion setContentId()     Sets the current record's "content_id" value
 * @method Discussion setContentType()   Sets the current record's "content_type" value
 * @method Discussion setDiscussionId()  Sets the current record's "discussion_id" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscussion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discussion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('content_type', 'enum', 10, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'slideshow',
              1 => 'article',
              2 => 'video',
              3 => 'photo',
              4 => 'recipe',
              5 => 'journal',
              6 => 'daily-dish',
              7 => 'raves',
             ),
             'primary' => false,
             'default' => 'recipe',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('discussion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}