<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserInterest', 'doctrine');

/**
 * BaseUserInterest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $interest_id
 * @property Interest $Interest
 * @property User $User
 * 
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getInterestId()  Returns the current record's "interest_id" value
 * @method Interest     getInterest()    Returns the current record's "Interest" value
 * @method User         getUser()        Returns the current record's "User" value
 * @method UserInterest setUserId()      Sets the current record's "user_id" value
 * @method UserInterest setInterestId()  Sets the current record's "interest_id" value
 * @method UserInterest setInterest()    Sets the current record's "Interest" value
 * @method UserInterest setUser()        Sets the current record's "User" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserInterest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_interest');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('interest_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Interest', array(
             'local' => 'interest_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}