<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DailyDish', 'doctrine');

/**
 * BaseDailyDish
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $slug
 * 
 * @method integer   getId()   Returns the current record's "id" value
 * @method string    getSlug() Returns the current record's "slug" value
 * @method DailyDish setId()   Sets the current record's "id" value
 * @method DailyDish setSlug() Sets the current record's "slug" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDailyDish extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('daily_dish');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('slug', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}