<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Weight', 'doctrine');

/**
 * BaseWeight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $override_id
 * @property integer $item_id
 * @property integer $rank
 * @property Override $Override
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method integer  getOverrideId()  Returns the current record's "override_id" value
 * @method integer  getItemId()      Returns the current record's "item_id" value
 * @method integer  getRank()        Returns the current record's "rank" value
 * @method Override getOverride()    Returns the current record's "Override" value
 * @method Weight   setId()          Sets the current record's "id" value
 * @method Weight   setOverrideId()  Sets the current record's "override_id" value
 * @method Weight   setItemId()      Sets the current record's "item_id" value
 * @method Weight   setRank()        Sets the current record's "rank" value
 * @method Weight   setOverride()    Sets the current record's "Override" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWeight extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('weight');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('override_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rank', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Override', array(
             'local' => 'override_id',
             'foreign' => 'id'));
    }
}