<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Messagefavs', 'doctrine');

/**
 * BaseMessagefavs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $groupmessageid
 * @property integer $messageid
 * @property integer $memberid
 * 
 * @method integer     getGroupmessageid() Returns the current record's "groupmessageid" value
 * @method integer     getMessageid()      Returns the current record's "messageid" value
 * @method integer     getMemberid()       Returns the current record's "memberid" value
 * @method Messagefavs setGroupmessageid() Sets the current record's "groupmessageid" value
 * @method Messagefavs setMessageid()      Sets the current record's "messageid" value
 * @method Messagefavs setMemberid()       Sets the current record's "memberid" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessagefavs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('messagefavs');
        $this->hasColumn('groupmessageid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('messageid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('memberid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}