<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MbForwardLog', 'doctrine');

/**
 * BaseMbForwardLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property timestamp $date
 * @property integer $counter
 * 
 * @method string       getUrl()     Returns the current record's "url" value
 * @method timestamp    getDate()    Returns the current record's "date" value
 * @method integer      getCounter() Returns the current record's "counter" value
 * @method MbForwardLog setUrl()     Sets the current record's "url" value
 * @method MbForwardLog setDate()    Sets the current record's "date" value
 * @method MbForwardLog setCounter() Sets the current record's "counter" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMbForwardLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mb_forward_log');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('counter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}