<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollOption', 'doctrine');

/**
 * BasePollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poll_id
 * @property integer $recipe_id
 * @property integer $photo_id
 * @property string $option_title
 * @property integer $votes
 * @property Photo $Photo
 * @property Poll $Poll
 * @property Recipe $Recipe
 * @property Doctrine_Collection $UserActions
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getPollId()       Returns the current record's "poll_id" value
 * @method integer             getRecipeId()     Returns the current record's "recipe_id" value
 * @method integer             getPhotoId()      Returns the current record's "photo_id" value
 * @method string              getOptionTitle()  Returns the current record's "option_title" value
 * @method integer             getVotes()        Returns the current record's "votes" value
 * @method Photo               getPhoto()        Returns the current record's "Photo" value
 * @method Poll                getPoll()         Returns the current record's "Poll" value
 * @method Recipe              getRecipe()       Returns the current record's "Recipe" value
 * @method Doctrine_Collection getUserActions()  Returns the current record's "UserActions" collection
 * @method PollOption          setId()           Sets the current record's "id" value
 * @method PollOption          setPollId()       Sets the current record's "poll_id" value
 * @method PollOption          setRecipeId()     Sets the current record's "recipe_id" value
 * @method PollOption          setPhotoId()      Sets the current record's "photo_id" value
 * @method PollOption          setOptionTitle()  Sets the current record's "option_title" value
 * @method PollOption          setVotes()        Sets the current record's "votes" value
 * @method PollOption          setPhoto()        Sets the current record's "Photo" value
 * @method PollOption          setPoll()         Sets the current record's "Poll" value
 * @method PollOption          setRecipe()       Sets the current record's "Recipe" value
 * @method PollOption          setUserActions()  Sets the current record's "UserActions" collection
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_option');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('poll_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('recipe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('photo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('votes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id'));

        $this->hasOne('Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id'));

        $this->hasOne('Recipe', array(
             'local' => 'recipe_id',
             'foreign' => 'id'));

        $this->hasMany('UserActions', array(
             'local' => 'id',
             'foreign' => 'poll_option_id'));
    }
}