<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContestImage', 'doctrine');

/**
 * BaseContestImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image_name
 * @property date $start_date
 * @property date $end_date
 * @property string $timezone
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method string       getImageName()  Returns the current record's "image_name" value
 * @method date         getStartDate()  Returns the current record's "start_date" value
 * @method date         getEndDate()    Returns the current record's "end_date" value
 * @method string       getTimezone()   Returns the current record's "timezone" value
 * @method ContestImage setId()         Sets the current record's "id" value
 * @method ContestImage setImageName()  Sets the current record's "image_name" value
 * @method ContestImage setStartDate()  Sets the current record's "start_date" value
 * @method ContestImage setEndDate()    Sets the current record's "end_date" value
 * @method ContestImage setTimezone()   Sets the current record's "timezone" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContestImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contest_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('timezone', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'CST',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}