<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PositionCount', 'doctrine');

/**
 * BasePositionCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $override_id
 * @property integer $count
 * @property Override $Override
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getOverrideId()  Returns the current record's "override_id" value
 * @method integer       getCount()       Returns the current record's "count" value
 * @method Override      getOverride()    Returns the current record's "Override" value
 * @method PositionCount setId()          Sets the current record's "id" value
 * @method PositionCount setOverrideId()  Sets the current record's "override_id" value
 * @method PositionCount setCount()       Sets the current record's "count" value
 * @method PositionCount setOverride()    Sets the current record's "Override" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePositionCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('position_count');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('override_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('count', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '5',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Override', array(
             'local' => 'override_id',
             'foreign' => 'id'));
    }
}