<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContentMedium', 'doctrine');

/**
 * BaseContentMedium
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $content_id
 * @property integer $medium_id
 * @property integer $sequence
 * @property Content $Content
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getContentId()  Returns the current record's "content_id" value
 * @method integer       getMediumId()   Returns the current record's "medium_id" value
 * @method integer       getSequence()   Returns the current record's "sequence" value
 * @method Content       getContent()    Returns the current record's "Content" value
 * @method ContentMedium setId()         Sets the current record's "id" value
 * @method ContentMedium setContentId()  Sets the current record's "content_id" value
 * @method ContentMedium setMediumId()   Sets the current record's "medium_id" value
 * @method ContentMedium setSequence()   Sets the current record's "sequence" value
 * @method ContentMedium setContent()    Sets the current record's "Content" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentMedium extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_medium');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('medium_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sequence', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));
    }
}