<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GroupRecipe', 'doctrine');

/**
 * BaseGroupRecipe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $group_id
 * @property integer $recipe_id
 * @property Group $Group
 * @property Recipe $Recipe
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getGroupId()   Returns the current record's "group_id" value
 * @method integer     getRecipeId()  Returns the current record's "recipe_id" value
 * @method Group       getGroup()     Returns the current record's "Group" value
 * @method Recipe      getRecipe()    Returns the current record's "Recipe" value
 * @method GroupRecipe setId()        Sets the current record's "id" value
 * @method GroupRecipe setGroupId()   Sets the current record's "group_id" value
 * @method GroupRecipe setRecipeId()  Sets the current record's "recipe_id" value
 * @method GroupRecipe setGroup()     Sets the current record's "Group" value
 * @method GroupRecipe setRecipe()    Sets the current record's "Recipe" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupRecipe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_recipe');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('recipe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('Recipe', array(
             'local' => 'recipe_id',
             'foreign' => 'id'));
    }
}