<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LegacyMbRecipe', 'doctrine');

/**
 * BaseLegacyMbRecipe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $recipe_id
 * @property integer $message_id
 * @property integer $group_id
 * @property Recipe $Recipe
 * 
 * @method integer        getRecipeId()   Returns the current record's "recipe_id" value
 * @method integer        getMessageId()  Returns the current record's "message_id" value
 * @method integer        getGroupId()    Returns the current record's "group_id" value
 * @method Recipe         getRecipe()     Returns the current record's "Recipe" value
 * @method LegacyMbRecipe setRecipeId()   Sets the current record's "recipe_id" value
 * @method LegacyMbRecipe setMessageId()  Sets the current record's "message_id" value
 * @method LegacyMbRecipe setGroupId()    Sets the current record's "group_id" value
 * @method LegacyMbRecipe setRecipe()     Sets the current record's "Recipe" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLegacyMbRecipe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('legacy_mb_recipe');
        $this->hasColumn('recipe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('message_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Recipe', array(
             'local' => 'recipe_id',
             'foreign' => 'id'));
    }
}