<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryMappingCsv', 'doctrine');

/**
 * BaseCategoryMappingCsv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $old_id
 * @property integer $new_id
 * 
 * @method integer            getId()     Returns the current record's "id" value
 * @method integer            getOldId()  Returns the current record's "old_id" value
 * @method integer            getNewId()  Returns the current record's "new_id" value
 * @method CategoryMappingCsv setId()     Sets the current record's "id" value
 * @method CategoryMappingCsv setOldId()  Sets the current record's "old_id" value
 * @method CategoryMappingCsv setNewId()  Sets the current record's "new_id" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryMappingCsv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_mapping_csv');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('old_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('new_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}