<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tempfavs', 'doctrine');

/**
 * BaseTempfavs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $legacy_recipe_id
 * @property integer $user_id
 * 
 * @method integer  getId()               Returns the current record's "id" value
 * @method integer  getLegacyRecipeId()   Returns the current record's "legacy_recipe_id" value
 * @method integer  getUserId()           Returns the current record's "user_id" value
 * @method Tempfavs setId()               Sets the current record's "id" value
 * @method Tempfavs setLegacyRecipeId()   Sets the current record's "legacy_recipe_id" value
 * @method Tempfavs setUserId()           Sets the current record's "user_id" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTempfavs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tempfavs');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('legacy_recipe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}