<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Wonders', 'doctrine');

/**
 * BaseWonders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $homepage_featured
 * @property string $title
 * @property string $slot_one_title
 * @property string $slot_one_url
 * @property string $slot_one_img
 * @property string $slot_two_title
 * @property string $slot_two_url
 * @property string $slot_two_img
 * @property string $slot_three_title
 * @property string $slot_three_url
 * @property string $slot_three_img
 * @property string $slot_four_title
 * @property string $slot_four_url
 * @property string $slot_four_img
 * @property string $slot_five_title
 * @property string $slot_five_url
 * @property string $slot_five_img
 * @property integer $active
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getId()                Returns the current record's "id" value
 * @method integer   getHomepageFeatured()  Returns the current record's "homepage_featured" value
 * @method string    getTitle()             Returns the current record's "title" value
 * @method string    getSlotOneTitle()      Returns the current record's "slot_one_title" value
 * @method string    getSlotOneUrl()        Returns the current record's "slot_one_url" value
 * @method string    getSlotOneImg()        Returns the current record's "slot_one_img" value
 * @method string    getSlotTwoTitle()      Returns the current record's "slot_two_title" value
 * @method string    getSlotTwoUrl()        Returns the current record's "slot_two_url" value
 * @method string    getSlotTwoImg()        Returns the current record's "slot_two_img" value
 * @method string    getSlotThreeTitle()    Returns the current record's "slot_three_title" value
 * @method string    getSlotThreeUrl()      Returns the current record's "slot_three_url" value
 * @method string    getSlotThreeImg()      Returns the current record's "slot_three_img" value
 * @method string    getSlotFourTitle()     Returns the current record's "slot_four_title" value
 * @method string    getSlotFourUrl()       Returns the current record's "slot_four_url" value
 * @method string    getSlotFourImg()       Returns the current record's "slot_four_img" value
 * @method string    getSlotFiveTitle()     Returns the current record's "slot_five_title" value
 * @method string    getSlotFiveUrl()       Returns the current record's "slot_five_url" value
 * @method string    getSlotFiveImg()       Returns the current record's "slot_five_img" value
 * @method integer   getActive()            Returns the current record's "active" value
 * @method timestamp getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()         Returns the current record's "updated_at" value
 * @method Wonders   setId()                Sets the current record's "id" value
 * @method Wonders   setHomepageFeatured()  Sets the current record's "homepage_featured" value
 * @method Wonders   setTitle()             Sets the current record's "title" value
 * @method Wonders   setSlotOneTitle()      Sets the current record's "slot_one_title" value
 * @method Wonders   setSlotOneUrl()        Sets the current record's "slot_one_url" value
 * @method Wonders   setSlotOneImg()        Sets the current record's "slot_one_img" value
 * @method Wonders   setSlotTwoTitle()      Sets the current record's "slot_two_title" value
 * @method Wonders   setSlotTwoUrl()        Sets the current record's "slot_two_url" value
 * @method Wonders   setSlotTwoImg()        Sets the current record's "slot_two_img" value
 * @method Wonders   setSlotThreeTitle()    Sets the current record's "slot_three_title" value
 * @method Wonders   setSlotThreeUrl()      Sets the current record's "slot_three_url" value
 * @method Wonders   setSlotThreeImg()      Sets the current record's "slot_three_img" value
 * @method Wonders   setSlotFourTitle()     Sets the current record's "slot_four_title" value
 * @method Wonders   setSlotFourUrl()       Sets the current record's "slot_four_url" value
 * @method Wonders   setSlotFourImg()       Sets the current record's "slot_four_img" value
 * @method Wonders   setSlotFiveTitle()     Sets the current record's "slot_five_title" value
 * @method Wonders   setSlotFiveUrl()       Sets the current record's "slot_five_url" value
 * @method Wonders   setSlotFiveImg()       Sets the current record's "slot_five_img" value
 * @method Wonders   setActive()            Sets the current record's "active" value
 * @method Wonders   setCreatedAt()         Sets the current record's "created_at" value
 * @method Wonders   setUpdatedAt()         Sets the current record's "updated_at" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWonders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wonders');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('homepage_featured', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_one_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_one_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_one_img', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('slot_two_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_two_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_two_img', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('slot_three_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_three_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_three_img', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('slot_four_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_four_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_four_img', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('slot_five_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_five_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slot_five_img', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}