<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryRecipe', 'doctrine');

/**
 * BaseCategoryRecipe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $recipe_id
 * @property integer $sequence
 * @property Category $Category
 * @property Recipe $Recipe
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getCategoryId()  Returns the current record's "category_id" value
 * @method integer        getRecipeId()    Returns the current record's "recipe_id" value
 * @method integer        getSequence()    Returns the current record's "sequence" value
 * @method Category       getCategory()    Returns the current record's "Category" value
 * @method Recipe         getRecipe()      Returns the current record's "Recipe" value
 * @method CategoryRecipe setId()          Sets the current record's "id" value
 * @method CategoryRecipe setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryRecipe setRecipeId()    Sets the current record's "recipe_id" value
 * @method CategoryRecipe setSequence()    Sets the current record's "sequence" value
 * @method CategoryRecipe setCategory()    Sets the current record's "Category" value
 * @method CategoryRecipe setRecipe()      Sets the current record's "Recipe" value
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryRecipe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_recipe');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('recipe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sequence', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Recipe', array(
             'local' => 'recipe_id',
             'foreign' => 'id'));
    }
}