<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Interest', 'doctrine');

/**
 * BaseInterest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $UserInterest
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getUserInterest() Returns the current record's "UserInterest" collection
 * @method Interest            setId()           Sets the current record's "id" value
 * @method Interest            setName()         Sets the current record's "name" value
 * @method Interest            setDescription()  Sets the current record's "description" value
 * @method Interest            setUserInterest() Sets the current record's "UserInterest" collection
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interest');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserInterest', array(
             'local' => 'id',
             'foreign' => 'interest_id'));
    }
}