<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Article extends BaseArticle {

//  public function setUp()
//  {
//    parent::setup();
//    $this->actAs('Sluggable', array(
//      'unique' => true,
//      'fields' => array('name'),
//      'canUpdate' => false
//      )
//    );
//  }

  public function getImgSrc($size='200x200', $absolute = false) {
    if (!is_null($this->image)) {
      $config = sfConfig::get('app_uploads_article');
      return Toolkit::getFileUrl($config['dir'], $this->image, $size, $absolute);
    }
  }

  public function processFile() {
    if (!$this->getImage())
      return;
    $image_config = sfConfig::get('app_uploads_article', array('dir' => sfConfig::get('sf_upload_dir').'/article'));
    $path = $image_config['dir'].'/';
    $original = sfConfig::get('app_uploads_tmp').'/'.$this->getImage();
    $md5sum = md5_file($original);
    $ext = explode('.', $original);
    $ext = '.'.array_pop($ext);
    $new_name = $md5sum.strtolower($ext);
    $new_path = Toolkit::getFilePath($path, $new_name);
    @mkdir($new_path, 0777, true);
    $new = $new_path.$new_name;
    if (is_file($new))
      unlink($new);
    @rename($original, $new);
    $this->setImage($new_name);
    $this->save();
    $sizes = $image_config['sizes'];
    Toolkit::resizeImages($path, $new_name, $sizes);
  }

  
  public function generateSlugFromName() {
    return UrlToolkit::generateCategoryArticleRecipeFriendlySlug($this->name);
  }

  public function updateSlugFromName() {
    $slug = $this->generateSlugFromName();
    $this->setSlug($slug)->save();
  }

}
