<?php

/**
 * CategoryMappingCsvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryMappingCsvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryMappingCsvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryMappingCsv');
    }
}