<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Category extends BaseCategory
{

  public function getChildren($criteria=array())
  {
    $q = Doctrine_Core::getTable('Category')->createQuery('c')->where('c.parent_id = ?', $this->id)->andWhere('c.is_active = ?', 1);
    if(isset($criteria['order_by'])){
      $q->orderBy('c.'.$criteria['order_by']);
    }
    return $q->execute();
  }

  public function getSelectedChildren($is_global=0)
  {
    $params['module'] = 'category';
    $params['is_global'] = $is_global;
    $params['category_id'] = $this->id;
    return CategoryTable::getSelectedList($params);
  }

  public function getParent()
  {
    $parent_id = is_null(@$this->parent_id) ? 0 : $this->parent_id;
    return Doctrine_Core::getTable('Category')->findOneByIdAndIsActive($parent_id, 1);
  }

  public function isMainCategory()
  {
    return is_null($this->parent_id) ? true : false;
  }

  public function getImgSrc($size='200x200')
  {
    $config = sfConfig::get('app_uploads_category');
    $full_path = $config['dir'] . '/' . $size . '/' . $this->id . '.jpg';

    if (file_exists($full_path)) {
      return str_replace(sfConfig::get('sf_web_dir'), '', $full_path);
    } else {
      return '/img/img-category.jpg';
    }
  }

}
