<?php

/**
 * CategoryWondersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryWondersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryWondersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryWonders');
    }
    
    public static function getWonders() {
	  	$q = Doctrine_Core::getTable('CategoryWonders')->createQuery('w')->orderBy('w.created_at DESC');
	  	return $q;
	}
	
	public static function getWonder() {
		$q = Doctrine_Core::getTable('CategoryWonders')->createQuery('w')->where('w.is_active = ?', array(1))->orderBy('w.created_at DESC')->fetchOne();
		return $q;
	}
	
}