<?php

/**
 * CategoryRecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryRecipeTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object CategoryRecipeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CategoryRecipe');
  }

  public static function getCategoryRecipe($main_category_id, $recipe_slug)
  {
    return Doctrine_Query::create()
      ->from('CategoryRecipe cr')
      ->innerjoin('cr.Recipe r')
      ->innerJoin('cr.Category c')
      ->where('r.is_active = ?', 1)
      ->where('c.is_active = ?', 1)
      ->andWhere('r.slug = ?', $recipe_slug)
      ->andWhere('c.parent_id = ?', $main_category_id)
      ->fetchOne();
  }

  public static function getNextSequenceNo($recipe_id)
  {
    return Doctrine_Core::getTable('CategoryRecipe')->createQuery('cr')->select('MAX(cr.sequence) AS max_sequence')->where('cr.recipe_id=?', $recipe_id)->fetchOne()->getMaxSequence() + 1;
  }

}