<?php

/**
 * Collection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Collection extends BaseCollection
{

  public function save(Doctrine_Connection $conn = null)
  {
    $this->updated_at = date('Y-m-d H:i:s');
    parent::save();
  }

  public function getActiveCollectionRecipe($collection_id, $limit = null)
  {
    $q = Doctrine_Core::getTable('CollectionRecipe')->createQuery('cr')->innerJoin('cr.Recipe r')->where('r.is_active = ?', 1)->andWhere('cr.collection_id = ?', $collection_id);
    if ($limit) {
      $q->limit($limit);
    }
    return $q->execute();
  }

}
