<?php

/**
 * CollectionRecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionRecipeTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object CollectionRecipeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CollectionRecipe');
  }

  public function getNextSequenceNo($collection_id)
  {
    return Doctrine_Core::getTable('CollectionRecipe')->createQuery('cr')->select('MAX(cr.sequence) AS max_sequence')->where('cr.collection_id=?', $collection_id)->fetchOne()->getMaxSequence() + 1;
  }

}