<?php

/**
 * Contestant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Contestant extends BaseContestant {

    public function getUserLocation($rest)
    {
        $userInfo = $rest->viewUserDetail($this->getRecipe()->getUser()->getOnesiteId());
        if (!empty($userInfo))
        {
            //finish 
            return;
        } else
            return '';
    }

    public function getActiveContestants()
    {
        return Doctrine_Core::getTable('Contestant')->createQuery('c')->where('c.contest_id = ?', $this->contest_id)->innerJoin('c.Recipe r')->innerJoin('r.CategoryRecipe cr')->andWhere('c.is_active = ?', 1)->andWhere('r.is_active = ?', 1)->orderBy('c.rank ASC')->execute()->getPrimaryKeys();
    }

    public function getPreviousContestantRecipe()
    {
        $contestants = $this->getActiveContestants();
        $current_contestant_key = array_search($this->id, $contestants);
        $previous_contestant_key = $current_contestant_key - 1;
        if ($previous_contestant_key < 0)
        {
            return null;
        } else
        {
            return Doctrine_Core::getTable('Contestant')->find($contestants[$previous_contestant_key])->getRecipe();
        }
    }

    public function getNextContestantRecipe()
    {
        $contestants = $this->getActiveContestants();
        $current_contestant_key = array_search($this->id, $contestants);
        $next_contestant_key = $current_contestant_key + 1;
        if ($next_contestant_key > count($contestants) - 1)
        {
            return null;
        } else
        {
            return Doctrine_Core::getTable('Contestant')->find($contestants[$next_contestant_key])->getRecipe();
        }
    }

    public function updateActive($active)
    {
        if ($active == 0)
        {
            $this->setIsActive($active);
            $this->save();
        }
    }

}
