<?php

/**
 * ContentMediumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentMediumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentMediumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentMedium');
    }
}