<?php

/**
 * DiscussionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Discussion');
    }
    
    
    public static function insertDiscussion($params)
    {
    	// check if discussion object exists
    	$q = Doctrine_Core::getTable('Discussion')->createQuery('d')->where('d.content_id = ?', $params['content_id'])->andWhere('d.discussion_id = ?', $params['discussion_id']);
    	$obj = $q->fetchOne();
    	if (!$obj) {
    		// insert new discussion
    		$d = new Discussion();
    		$d->setContentId($params['content_id']);
    		$d->setContentType($params['type']);
    		$d->setDiscussionId($params['discussion_id']);
    		$d->save();
    	}
    }
    
    public static function getDiscussion($params)
    {
    	$q = Doctrine_Core::getTable('Discussion')->createQuery('d')->where('d.content_id = ?', $params['content_id']);
    	return $q->fetchOne();
    }
}