<?php

/**
 * GroupmessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupmessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupmessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Groupmessage');
    }
}