<?php

/**
 * GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Group');
    }
    
    
    public static function getGroupIdBySlug($slug)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.group_slug = ?', $slug);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj['id'];
    	}
    }
    
    public static function getGroupCategoryBySlug($slug)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g');
    	$q->innerJoin('g.Category c');
    	$q->where('g.group_slug = ?', $slug);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj['Category']['slug'];
    	}
    }
    
    public static function getGroupCategoryObjBySlug($slug)
    {
    	$q = Doctrine_Core::getTable('Category')->createQuery('c');
    	$q->leftJoin('c.Group g');
    	$q->where('g.group_slug = ?', $slug);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj;
    	}
    }
    
    
    public static function getGroupObjByBlogId($id)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g');
    	$q->innerJoin('g.Category c');
    	$q->where('g.blog_id = ?', $id);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj;
    	}
    }
    
    public static function getGroupSlugById($id)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.id = ?', $id);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj['group_slug'];
    	}
    }
    
    public static function getForumIdBySlug($slug)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.group_slug = ?', $slug);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj['forum_id'];
    	}
    }

    
    public static function insertGroup($params)
    {
    	// check if discussion object exists
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.id = ?', $params['group_id']);
    	$obj = $q->fetchOne();
    	if (!$obj) {
    		// insert new discussion
    		$d = new Group();
    		$d->setId($params['group_id']);
    		$d->setBlogId($params['blog_id']);
    		if (isset($params['forum_id'])) {
    			$d->setForumId($params['forum_id']);
    		}
    		if (isset($params['category_id'])) {
    			$d->setCategoryId($params['category_id']);
    		}
    		$d->setGroupSlug($params['group_slug']);
    		$d->save();
    	}
    }
    
    public static function updateGroupBlogId($params)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.id = ?', $params['group_id']);
    	$obj = $q->fetchOne();
		if ($obj) {
			$obj->setBlogId($params['blog_id']);
			$obj->save();
		}
    }
    
    public static function updateGroupCategoryId($params)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.id = ?', $params['group_id']);
    	$obj = $q->fetchOne();
		if ($obj) {
			$obj->setCategoryId($params['category_id']);
			$obj->save();
		} 
    }
    
    public static function updateGroupForumId($params)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g')->where('g.id = ?', $params['group_id']);
    	$obj = $q->fetchOne();
		if ($obj) {
			$obj->setForumId($params['forum_id']);
			$obj->save();
		} 
    }
    
    public static function getGroupSponsorBySlug($slug)
    {
    	$q = Doctrine_Core::getTable('Group')->createQuery('g');
    	$q->innerJoin('g.Sponsor s');
    	$q->where('g.group_slug = ?', $slug);
    	$obj = $q->fetchOne();
    	if ($obj) {
    		return $obj['Sponsor']['name'];
    	}
    }
    
}