<?php

/**
 * GroupRecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupRecipeTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object GroupRecipeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('GroupRecipe');
  }

  public static function insertGroupRecipes($group_id, $recipe_id)
  {
    // check if group-recipe relationship exists
    $q = Doctrine_Core::getTable('GroupRecipe')->createQuery('g')->where('g.group_id = ?', $group_id)->andWhere('g.recipe_id = ?', $recipe_id);
    $obj = $q->fetchOne();
    if (!$obj) {
      // insert releationship
      $g = new GroupRecipe();
      $g->setGroupId($group_id);
      $g->setRecipeId($recipe_id);
      $g->save();
    }
  }

  public static function updateRecipeGroups($user_groups, $selected_groups, $recipe_id)
  {
    // First remove all the user_group recipe relationships
    if (is_array($user_groups) && count($user_groups) > 0) {
      foreach ($user_groups as $user_group) {
        $group_recipe = Doctrine_Core::getTable('GroupRecipe')->findOneByGroupIdAndRecipeId($user_group['group_id'], $recipe_id);
        if ($group_recipe) {
          $group_recipe->delete();
        }
      }
    }
    // Then add the selected ones
    if (is_array($selected_groups) && count($selected_groups) > 0) {
      foreach ($selected_groups as $selected_group_id => $value) {
        $group_recipe = Doctrine_Core::getTable('GroupRecipe')->findOneByGroupIdAndRecipeId($selected_group_id, $recipe_id);
        if (!$group_recipe) {
          $group_recipe = new GroupRecipe();
          $group_recipe->setGroupId($selected_group_id);
          $group_recipe->setRecipeId($recipe_id);
          $group_recipe->save();
        }
      }
    }
  }

}