<?php

/**
 * LegacyMbRecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LegacyMbRecipeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LegacyMbRecipeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LegacyMbRecipe');
    }
}