<?php

/**
 * MadeitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MadeitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MadeitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Madeit');
    }
}