<?php

/**
 * MbForwardLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MbForwardLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MbForwardLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MbForwardLog');
    }
}