<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Message');
    }
    
    public static function insertMessage($params)
    {
		$m = new Message();
		$m->setMessageType($params['messageType']);
		if (isset($params['recipient_email'])) {
			$m->setRecipientEmail($params['recipient_email']);
		}
		if (isset($params['recipient_name'])) {
			$m->setRecipientName($params['recipient_name']);
		}
		if (isset($params['recipient_id'])) {
			$m->setRecipientId($params['recipient_id']);
		}
		if (isset($params['comment'])) {
			$m->setComment($params['comment']);
		}
		$m->setSent(0);
		$m->setCreatedAt(date('Y-m-d H:i:s'));
    	$m->setUpdatedAt(date('Y-m-d H:i:s'));
		$m->save();
    }
    
    public static function getMessages()
    {
    	return Doctrine_Core::getTable('Message')->createQuery('m')->where('m.sent = ?', 0)->orderBy('m.created_at')->execute();
    }
    
    public static function indicateMessageSent($id)
    {
    	$q = Doctrine_Core::getTable('Message')->createQuery('m')->where('m.id = ?', $id);
    	$obj = $q->fetchOne();
		if ($obj) {
			$obj->setSent(1);
			$obj->setUpdatedAt(date('Y-m-d H:i:s'));
			$obj->save();
		}
    }
}