<?php

/**
 * MetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetaTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object MetaTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Meta');
  }

  public static function updateActive($meta_id, $status)
  {
    if (isset($meta_id) && isset($status)) {
      Doctrine_Query::create()->update('Meta m')->set('m.is_active', '?', $status)->where('m.id = ?', $meta_id)->execute();
    }
  }

  public static function getMetaBySlug($slug)
  {
    return Doctrine_Core::getTable('Meta')->createQuery('m')->where('m.slug = ?', $slug)->fetchOne();
  }

}