<?php

/**
 * OverrideTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OverrideTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object OverrideTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Override');
  }

  public static function getOverride($params=array())
  {
    if (!isset($params['start_date'])) {
      $params['start_date'] = date('Y-m-d H:i:s');
    }
    if (!isset($params['end_date'])) {
      $params['end_date'] = date('Y-m-d H:i:s');
    }
    if (!isset($params['module'])) {
      $params['module'] = 'recipe';
    }
    if (!isset($params['is_global'])) {
      $params['is_global'] = 1;
    }
    if (!isset($params['is_mobile'])) {
      $params['is_mobile'] = 0;
    }
    $q = Doctrine_Core::getTable('Override')->createQuery('o')
      ->where('o.is_global = ?', $params['is_global'])
      ->andWhere('o.module = ?', $params['module'])
      ->andWhere('o.start_date <= ?', $params['start_date'])
      ->andWhere('o.end_date >= ?', $params['end_date']);
    if (isset($params['category_id'])) {
      $q->andWhere('o.category_id = ?', $params['category_id']);
    }
    if ($params['is_mobile']) {
      return $q->orderBy('o.is_mobile DESC, o.id DESC')->fetchOne();
    } else {
      return $q->andWhere('o.is_mobile = ?', 0)->orderBy('o.id DESC')->fetchOne();
    }
  }

  public static function getOverrideAdmin($params=array())
  {
    if (!isset($params['module'])) {
      $params['module'] = 'recipe';
    }
    if (!isset($params['is_global'])) {
      $params['is_global'] = 1;
    }
    $q = Doctrine_Core::getTable('Override')->createQuery('o')
      ->where('o.is_global = ?', $params['is_global'])
      ->andWhere('o.module = ?', $params['module']);
    if (isset($params['category_id'])) {
      $q->andWhere('o.category_id = ?', $params['category_id']);
    }
    return $q->orderBy('id ASC')->execute();
  }

  public static function getOverrideCount($overrideId)
  {
    $overrideObj = Doctrine_Core::getTable('Override')->createQuery('o')->where('o.id = ?', $overrideId)->fetchOne();
    $positionCount = $overrideObj->getPositionCount();
    if (count($positionCount) > 0) {
      return intval($positionCount->getLast()->getCount());
    } else {
      $params = array('module' => $module, 'is_global' => 1, 'is_mobile' => 0);
      return PositionCount::getDefault($params);
    }
  }

}