<?php

/**
 * Override
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Override extends BaseOverride
{

  public function getWeightedItems($obj_name = 'Recipe', $max_item_count = null)
  {
    $q = Doctrine_Core::getTable('Weight')->createQuery('w')->select('item_id')->where('override_id = ?', $this->id)->orderBy('rank');
    if ($max_item_count) {
      $q->limit($max_item_count);
    }
    $weights = $q->execute(array(), Doctrine::HYDRATE_ARRAY);
    if (count($weights) > 0) {
      $item_ids = array();
      $item_coll = array();
      foreach ($weights as $weight) {
        $obj = Doctrine_Core::getTable($obj_name)->findOneByIdAndIsActive($weight['item_id'], 1);
        if ($obj_name) {
          $item_coll[] = $obj;
          $item_ids[] = intval($weight['item_id']);
        }
      }
    }
    return compact('item_ids', 'item_coll');
  }

  public function getItemsShown($overrideId, $module)
  {
    
  }

}
