<?php

/**
 * Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Photo extends BasePhoto
{

  public function save(Doctrine_Connection $conn = null)
  {
    $this->updated_at = date('Y-m-d H:i:s');
    parent::save();
  }

  public function getImgSrc($size = '400x300', $absolute = false)
  {
    if ($this->source == 'nw') {
      $config = sfConfig::get('app_uploads_photo');
      return Toolkit::getFileUrl($config['dir'], $this->image, $size, $absolute);
    } else {
      return $this->image;
    }
  }

  public function processFile()
  {
    if (!$this->getImage())
      return;
    $image_config = sfConfig::get('app_uploads_photo', array('dir' => sfConfig::get('sf_upload_dir') . '/photo'));
    $path = $image_config['dir'] . '/';
    $original = sfConfig::get('app_uploads_tmp') . '/' . $this->getImage();
    $md5sum = md5_file($original);
    $image_type = new ImageType();
    $new_name = $md5sum . $image_type->getExtention($original);
    $new_path = Toolkit::getFilePath($path, $new_name);
    @mkdir($new_path, 0777, true);
    $new = $new_path . $new_name;
    if (is_file($new))
      unlink($new);
    @rename($original, $new);
    $this->setImage($new_name);
    $this->save();
    $sizes = $image_config['sizes'];
    Toolkit::resizeImages($path, $new_name, $sizes);
  }

  public function create($recipe_id)
  {
    $this->setUserId(sfContext::getInstance()->getUser()->getAttribute('id'));
    $this->setRecipeId($recipe_id);
    $this->setSequence(PhotoTable::getNextSequenceNo($recipe_id));
    $this->setSource('nw');
    $this->setThumb(null);
    $this->setCreatedAt(date('Y-m-d H:i:s'));
    $this->save();
    $this->processFile();
  }

}
