<?php

/**
 * PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PollTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Poll');
  }

  
  public static function getHomepagePoll() 
  {
  	$q = Doctrine_Core::getTable('Poll')->createQuery('p')->innerJoin('p.PollOption o')->where('p.homepage_featured = ? AND p.active = ?', array(1, 1))->orderBy('p.created_at DESC')->fetchOne();
  	return $q;
  }
  
  public static function getPolls() {
  	$q = Doctrine_Core::getTable('Poll')->createQuery('p')->orderBy('p.created_at DESC');
  	return $q;
  }
  
  public static function voteForPoll($poll_id) {
  	$q = Doctrine_Core::getTable('Poll')->find(array($poll_id));
  	if ($q) {
  		$vote = 1 + $q->getTotalVotes();
  		$q->setTotalVotes($vote);
  		$q->save();
  	}
  }
  
  public static function getPollDetails($id) 
  {
  	$q = Doctrine_Core::getTable('Poll')->find(array($id));
  	return $q;
  }

}