<?php

/**
 * PollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PollOption extends BasePollOption
{

  public function getRecipe()
  {
    return Doctrine_Core::getTable('Recipe')->find($this->recipe_id);
  }

  public function getPhoto()
  {
    return Doctrine_Core::getTable('Photo')->find($this->photo_id);
  }

}
