<?php

/**
 * PositionCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class PositionCount extends BasePositionCount
{
  private static $global_recipe_count = 5;
  private static $detail_recipe_count = 6;
  private static $global_category_count = 1000;
  private static $detail_category_count = 1000;
  private static $global_article_count = 6;
  private static $global_slideshow_count = 2;
  // Mobile variables
  private static $global_recipe_count_mobile = 3;
  private static $detail_recipe_count_mobile = 3;
  private static $global_category_count_mobile = 1000;
  private static $detail_category_count_mobile = 1000;
  private static $global_article_count_mobile = 3;
  private static $global_slideshow_count_mobile = 3;

  public static function getDefault($params)
  {
    if (!isset($params['module'])) {
      $params['module'] = 'recipe';
    }
    if (!isset($params['is_global'])) {
      $params['is_global'] = 1;
    }
    if (!isset($params['is_mobile'])) {
      $params['is_mobile'] = 0;
    }
    $default = ($params['is_global'] == 1 ? 'global_' : 'detail_') . $params['module'] . '_count';
    $default .= $params['is_mobile'] == 1 ? '_mobile' : '';
    return self::${$default};
  }

}