<?php

/**
 * Rate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Rate extends BaseRate
{

  public function create($recipe_id, $user_id, $rating)
  {
    $this->setRecipeId($recipe_id);
    $this->setUserId($user_id);
    $this->setRating($rating);
    $this->save();
  }

}
