<?php

/**
 * RecipeLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecipeLikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecipeLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecipeLike');
    }
    
    // checks if user has a record for a specific recipe ID (liked / not liked)
    public static function hasRecord($user_id, $recipe_id)
    {
	    return Doctrine_Core::getTable('RecipeLike')->createQuery('r')->where('r.user_id = ? AND r.recipe_id = ?', array($user_id, $recipe_id))->fetchOne() ? true : false; 
    }
    
    public static function addLike($user_id, $recipe_id, $is_liked)
    {
	    $obj = self::hasRecord($user_id, $recipe_id);
	    if (!$obj) {
	    	$action = new RecipeLike();
	    	$action->setUserId($user_id);
	    	$action->setRecipeId($recipe_id);
	    	$action->setIsLiked($is_liked);
	    	$action->setCreatedAt(date('Y-m-d H:i:s'));
	    	$action->save();
	    } else {
		    $q = Doctrine_Query::create()
		    ->update('RecipeLike r')
		    ->set('r.is_liked', '?', $is_liked)
		    ->set('r.updated_at', '?', date('Y-m-d H:i:s'))
		    ->where('r.user_id = ?', $user_id)
		    ->andWhere('r.recipe_id = ?', $recipe_id)
		    ->execute();
	    }
    }
    
    public static function getLike($user_id, $recipe_id)
    {
	    return Doctrine_Core::getTable('RecipeLike')->createQuery('r')->where('r.user_id = ? AND r.recipe_id = ?', array($user_id, $recipe_id))->fetchOne();
    }
}