<?php

/**
 * SavedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SavedTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object SavedTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Saved');
  }

  public static function isSaved($recipe_id, $user_id)
  {
    return Doctrine_Core::getTable('Saved')->findOneByRecipeIdAndUserId($recipe_id, $user_id) ? true : false;
  }
 
  public static function add($recipe_id, $user_id)
  {
    $is_saved = self::isSaved($recipe_id, $user_id);
    if (!$is_saved) {
      $saved = new Saved();
      $saved->setRecipeId($recipe_id);
      $saved->setUserId($user_id);
      $saved->save();
    }
  } 

}