<?php

/**
 * SlideshowMedium
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class SlideshowMedium extends BaseSlideshowMedium
{

  public function getImgSrc($size='400x300')
  {
    $p = Doctrine_Core::getTable('Photo')->createQuery('p')->where('p.id = ?', $this->medium_id)->fetchOne();
    return is_object($p) ? $p->getImgSrc($size) : null;
  }

  public function getImgParentObj($type='recipe-photo')
  {
    switch ($type) {
      case 'recipe-photo':
        return Doctrine_Core::getTable('Recipe')->createQuery('r')->innerJoin('r.Photo p')->where('p.id = ?', $this->medium_id)->fetchOne();
    }
  }

}
