<?php

/**
 * SlideshowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlideshowTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object SlideshowTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Slideshow');
  }

  /**
   * Returns the list of the slideshows.
   *
   * @param array $params
   * @return list
   */
  public static function getList($params=array())
  {
    $max_item_count = null;
    $params['module'] = 'slideshow';
    $weight_count = 0;
    $slideshow_coll = array();
    $override = OverrideTable::getOverride($params);
    if ($override) {
      // Determine the available positions for the given area
      $position_counts = $override->getPositionCount();
      if (count($position_counts) > 0) {
        if (isset($params['is_mobile']) && $params['is_mobile'] == 1) {
          if ($override->getIsMobile()) {
            $item_count = intval($position_counts->getLast()->getCount());
          } else {
            $item_count = PositionCount::getDefault($params);
            $max_item_count = $item_count;
          }
        } else {
          $item_count = intval($position_counts->getLast()->getCount());
        }
      } else {
        $item_count = PositionCount::getDefault($params);
      }
      // Override the sorting
      $weighted_slideshows = $override->getWeightedItems(ucfirst($params['module']), $max_item_count);
      $weight_count = count(@$weighted_slideshows['item_ids']);
      $unweight_count = $item_count - $weight_count;
      if (isset($weighted_slideshows['item_coll'])) {
        $slideshow_coll = $weighted_slideshows['item_coll'];
      }
      if ($unweight_count > 0) {
        $q = Doctrine_Core::getTable(ucfirst($params['module']))->createQuery('a')->Where('a.is_active = ?', 1);
        if (isset($params['category_id'])) {
          $q->andWhere('a.category_id = ?', $params['category_id']);
        }
        if ($weight_count > 0) {
          $q->whereNotIn('a.id', $weighted_slideshows['item_ids']);
        }
        $unweighted_slideshows = $q->orderBy('a.views DESC')->limit($unweight_count)->execute();
        foreach ($unweighted_slideshows as $unweighted_slideshow) {
          $slideshow_coll[] = $unweighted_slideshow;
        }
      }
      return $slideshow_coll;
    } else {
      $item_count = PositionCount::getDefault($params);
    }
    $q = Doctrine_Core::getTable(ucfirst($params['module']))->createQuery('a')->where('a.is_active = ?', 1);
    if (isset($params['category_id'])) {
      $q->andWhere('a.category_id = ?', $params['category_id']);
    }
    $unweighted_slideshows = $q->orderBy('a.views DESC')->limit($item_count)->execute();
    foreach ($unweighted_slideshows as $unweighted_slideshow) {
      $slideshow_coll[] = $unweighted_slideshow;
    }
    return $slideshow_coll;
  }

  public static function getFilteredSlideshows($params)
  {
    $q = Doctrine_Core::getTable('Slideshow')->createQuery('s');
    if (isset($params['slideshowName']) && ($params['slideshowName'] != "Slideshow Name")) {
      $q->where('s.title LIKE ?', "%" . $params['slideshowName'] . "%");
    }
    $q->innerJoin('s.Category c');
    if (isset($params['sort'])) {
      switch ($params['sort']) {
        case "title":
          $q->orderBy('s.title ' . $params['sortDir']);
          break;
        case "category":
          $q->orderBy('c.name ' . $params['sortDir']);
          break;
        case "startDate":
          $q->orderBy('s.start_date ' . $params['sortDir']);
          break;
        case "endDate":
          $q->orderBy('s.end_date ' . $params['sortDir']);
          break;
        case "sponsor":
          $q->leftjoin('s.Sponsor sp');
          $q->orderBy('sp.name ' . $params['sortDir']);
          $q->addOrderBy('s.start_date DESC');
          break;
        case "active":
          $q->orderBy('s.is_active ' . $params['sortDir']);
          $q->addOrderBy('s.start_date DESC');
          break;
        default:
          $q->orderBy('s.start_date ' . $params['sortDir']);
      }
    } else
      $q->orderBy('s.start_date DESC');

    return $q;
  }

  public static function updateActive($slideshowId, $active)
  {

    if (isset($slideshowId) && isset($active)) {
      $q = Doctrine_Query::create()
        ->update('Slideshow s')
        ->set('s.is_active', '?', $active)
        ->where('s.id = ?', $slideshowId)
        ->execute();

      return $q;
    }
  }

  public static function updateSponsor($slideshowId, $sponsorId)
  {
    if (isset($slideshowId) && isset($sponsorId)) {
      $q = Doctrine_Query::create()->update('Slideshow s');
      ($sponsorId != 0) ? $q->set('s.sponsor_id', '?', $sponsorId) : $q->set('s.sponsor_id', 'NULL');
      $q->where('s.id = ?', $slideshowId)->execute();
      return $q;
    }
  }

  public static function updatePhoto($slideshowId, $photoId)
  {
    if (isset($slideshowId) && isset($photoId)) {
      $q = Doctrine_Query::create()->update('Slideshow s');
      ($photoId != 0) ? $q->set('s.photo_id', '?', $photoId) : $q->set('s.photo_id', 'NULL');
      $q->where('s.id = ?', $slideshowId)->execute();
      return $q;
    }
  }
  
  public static function getWeightedItems($override)
  {
    //Returns an Array of the Override Items
    $weightedItemsArray = $override->getWeightedItems('Slideshow');
    if (count($weightedItemsArray) > 0)
      return $weightedItemsArray['item_coll'];
    else
      return;
  }

}