<?php

/**
 * Sponsor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betterrecipes
 * @subpackage model
 * @author     Rusty Cage <rcage@resolute.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Sponsor extends BaseSponsor {
  
  public function getActiveSponsors(){
    $q = Doctrine_Core::getTable('Sponsor')->createQuery('s')->where('s.is_active = 1');
    $sponsors = $q->execute();
    return $sponsors;
  }

}
