<?php

/**
 * TemplogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemplogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemplogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Templog');
    }
}