<?php

/**
 * TempfavsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TempfavsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TempfavsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tempfavs');
    }
}