<?php

/**
 * TipContestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipContestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipContestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipContest');
    }
}