<?php

/**
 * TipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tip');
    }

    public static function getFilteredTips($params)
  	{
	    $q = Doctrine_Core::getTable('Tip')->createQuery('a');
	    if (isset($params['TipTitle']) && ($params['TipTitle'] != "Tip Title")) {
	      $q->where('a.title LIKE ?', "%" . $params['tipTitle'] . "%");
	    }
	    return $q;
  	}
}