<?php

/**
 * UserProviderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProviderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProviderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProvider');
    }
}