<?php

/**
 * UserInterestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserInterestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserInterestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserInterest');
    }
}