<?php

/**
 * VoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote');
    }
    
    public static function uidCheck($contestantId, $uid){
      $q = Doctrine_Core::getTable('vote')->createQuery('v');
      $q->where('v.contestant_id = ?', $contestantId);
      $q->andWhere('v.uid = ?', $uid);
      $q->andWhere('v.created_at >= ?', date('Y-m-d 00:00:00'))->andWhere('v.created_at <= ?', date('Y-m-d 23:59:59'));
      $row = $q->execute();

      if (count($row) > 0){
        return false; //row already exists, prevent vote
      } else {
        return true; //user has not voted for this contestant, good to go
      }
    }
}