<?php

/**
 * WondersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WondersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WondersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wonders');
    }
    
    public static function getWonders() {
	  	$q = Doctrine_Core::getTable('Wonders')->createQuery('w')->orderBy('w.created_at DESC');
	  	return $q;
	}
	
	public static function getHomepageWonder() {
		$q = Doctrine_Core::getTable('Wonders')->createQuery('w')->where('w.homepage_featured = ? and w.active = ?', array(1, 1))->orderBy('w.created_at DESC')->fetchOne();
		return $q;
	}
	
	public static function getWonder() {
		$q = Doctrine_Core::getTable('Wonders')->createQuery('w')->where('w.homepage_featured = ? and w.active = ?', array(0, 1))->orderBy('w.created_at DESC')->fetchOne();
		return $q;
	}
}