# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Better Recipes
    description:  "An online cookbook of recipes for any meal. Browse recipes by topic or search to find the perfect recipe at Better Recipes. Become a member to upload recipes and enter monthly recipe contests for cash prizes."
    keywords:     
    #language:     en
    #robots:       index, follow

  stylesheets:
    - betterrecipes.css
    - print.css: { media: print }
    # - jquery.wysiwyg.css
    

  javascripts:
    - jquery-1.6.2.min.js
    - jquery.cycle.all.js
    # - jquery.jlembed.js
    # - /ckeditor/ckeditor.js
    # - /ckfinder/ckfinder.js
    - betterrecipes.js
    - s_code_betterrecipesH.js
    # - /jwysiwyg/src/jquery.wysiwyg.js
    

  has_layout:     true
  layout:         layout
