<div class="article fullwidth">
  <div id="terms">
    <p align="CENTER"><b><font face="Arial, Helvetica, sans-serif" size="4">Meredith Corporation Visitor Agreement</font></b></p>
    <p align="CENTER"><b><font face="Arial" size="2">BetterRecipes.com Online</font> </b></p>
    <p><font face="Arial, Helvetica, sans-serif">This website is provided   to you by the Meredith Corporation ("we" or "us"). Please take a moment to read this Visitor Agreement. By using this website, you accept this Visitor Agreement. Our sites are always evolving; please be aware that we may change this Visitor Agreement from time to time. By continuing to use this site after we post any such changes, you accept this Visitor Agreement, as modified.</font></p>
    <p><font face="Arial, Helvetica, sans-serif">Our Visitor Agreement addresses the following topics:</font></p>
    <table border="1" cellspacing="1" cellpadding="7" width="540">
      <tr> 
        <td width="49%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#using">1.    Using Good Judgment</a></font></td>
        <td width="51%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#limitation">6. Limitation of Liability</a></font></td>
      </tr>
      <tr> 
        <td width="49%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#rules">2. 
            Rules for Registration, Submissions and Messages</a></font></td>
        <td width="51%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#discontinuance">7. Discontinuance, Modification & Restrictions</a></font></td>
      </tr>
      <tr> 
        <td width="49%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#rights">3. 
            Rights</a></font></td>
        <td width="51%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#applicable">8. Applicable Law & Exclusive Jurisdiction</a></font></td>
      </tr>
      <tr> 
        <td width="49%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#third">4.      Third Party Services</a></font></td>
        <td width="51%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#dispute">9. Dispute Resolution</a></font></td>
      </tr>
      <tr> 
        <td width="49%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#disclaimer">5. Disclaimer of Warranties</a></font></td>
        <td width="51%" valign="TOP"><font face="Arial, Helvetica, sans-serif" size="2"><a href="#misc">10.       Miscellaneous</a></font></td>
      </tr>
    </table>
    <p align="left"><font face="Arial, Helvetica, sans-serif">We respect your privacy. Please take a moment to read our <a href="http://www.betterrecipes.com/privacy-policy">Privacy Policy</a>. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="using"></a>1. Using Good Judgment</b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">Our Visitor Agreement is intended to make our sites safe and fun for everybody. We invite you to bring to our attention any content on our sites you believe to be inaccurate, inappropriate or in violation of these rules. Please write to us at onlineeditor@meredith.com. </font></p>
    <p><font face="Arial, Helvetica, sans-serif">Use common sense when you use our and anybody else's websites. The content that appears on our sites is for informational purposes only. Despite our efforts to provide useful and accurate information, errors may appear from time to time. Some of the content you find on our sites was not created, edited, or posted by us (for example, discussion group postings). The materials posted by third parties on our sites represent the views of such third parties and are not endorsed by us, nor do we guarantee the accuracy of any posting. Though we hope the advertisers, merchants and users you meet through our sites treat you honorably and fairly, we can't vouch for the information, goods, or services they offer. Before you act on information you've found on or through any of our sites, confirm any facts that are important to your decision. We encourage you to exercise a healthy skepticism and good judgment.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="rules"></a>2. Rules for Registration, Submissions and Messages</b></font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Registration.  </b>To obtain access to certain Meredith services, you will be given an opportunity to register with our site. As part of the registration process, you will select a password. You agree that the information you supply during that registration process will be accurate and complete and that you will not register under the name of, nor attempt to enter any of our sites under the name of, another person. You will be responsible for preserving the confidentiality of your password and for all actions of persons accessing any of our sites through any password assigned to you. You will notify us at onlineeditor@meredith.com of any known or suspected unauthorized use of your account. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Submissions and Messages. </b>Responsibility for what is posted in the discussion groups or other public forums on our sites lies with each user--you alone are responsible for the content of your messages, and the consequences of any such messages. You agree not to use our sites to send or submit materials: </font></p>
    <blockquote> 
      <blockquote> 
        <p><font face="Arial, Helvetica, sans-serif">a. that are false, inaccurate or misleading; <br>
          b. that infringe any third party's copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy; <br>
          c. that violate any law, statute, ordinance or regulation (including without limitation those governing export control, consumer protection, unfair competition, anti-discrimination and false advertising); <br>
          d. that are libelous, threatening or harassing; <br>
          e. that are obscene or contain any kind of pornography; 
          <br>
          f. that contain any viruses, Trojan horses, worms, time bombs, cancelbots or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information; <br>
          g. that might create liability for us or might cause us to lose (in whole or in part) the services of our Internet service providers or other suppliers; <br>
          h. that interfere with the ability of others to enjoy our site; <br>
          i. that impersonate any other person or entity, whether actual or fictitious, including impersonating an employee or consultant of Meredith Corporation; <br>
          j. that link to or include descriptions of goods or services that: (i) are prohibited under this Agreement; or (ii) you do not have a right to link to or include; <br>
          k. that contain any content that you do not have the right to make available under any law or any contractual or fiduciary relationship (such as inside information and confidential information learned under a non-disclosure agreement); or<br>
          l. that instigate or encourage others to commit illegal activities or cause injury or property damage to any person.</font></p>
      </blockquote>
    </blockquote>
    <p><font face="Arial, Helvetica, sans-serif">That said, we are most often a passive conduit for the information users submit. We cannot and do not review every submission a user may make. 
      We neither endorse nor guarantee the accuracy or propriety of any submission. We do, however, reserve the right, but do not assume the obligation, to restrict or prohibit your use of our sites if we believe you are violating any of the terms of this Visitor Agreement and to remove, edit, or relocate any submission as we see fit, whether for legal or other reasons.</font></p>
    <p><font face="Arial, Helvetica, sans-serif">We want users to feel free to share their email addresses in public posting areas. Accordingly, you may not use any other user's information, personal or otherwise, for any commercial purpose, to send chain letters, junk mail, "spam," or other bulk communications or for developing lists. Any such use by you will be a violation of this Visitor Agreement. Your use of the sites is limited to personal, non-commercial purposes. Your commercial exploitation of the sites is strictly prohibited, unless we grant prior written permission. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="rights"></a>3. Rights</b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">You acknowledge that: </font></p><blockquote> 
      <blockquote> 
        <p><font face="Arial, Helvetica, sans-serif">1. We permit access to content that is protected by copyrights, trademarks and other intellectual and proprietary rights ("Rights") and; <br>
          <br>
          2. This Visitor Agreement and applicable copyright, trademark and other laws govern your use of such content. </font></p>
      </blockquote>
    </blockquote>
    <p><font face="Arial, Helvetica, sans-serif"><b>Our Limited License to You. </b>You are free to display and print for your personal, non-commercial use information you receive through our sites. You may not reproduce, distribute, or otherwise use any of the materials without the prior written consent of the Rights holder. Requests for permission to reproduce, distribute or otherwise use materials found on our sites should be made to eReprints@ meredith.com. The burden of determining whether any content on our sites is or is not protected by Rights rests with you. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Links. </b> You are free to encourage others to access the information on our sites. We welcome links to our sites. You are free to establish a hypertext link to any of our sites so long as the link does not state or imply any sponsorship or endorsement of your site by us or make use of a logo without written consent of the logo owner. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>No Framing. </b> Without our prior written consent, you may not frame, or in-line link to, any of the content of our sites, or incorporate into any other website or service any of our intellectual property.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Marks.</b> We do not want anyone to be confused about which materials and services are provided by us and which are not. You may not use any mark appearing on our sites without the prior written consent of the owner of the mark. BetterRecipes.com and all associated logos are marks owned by Meredith Corporation.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Your License to Us. </b>By submitting material to or through our sites, you grant us and our partners, agents, affiliates and service providers (collectively, "Affiliates"), the non-exclusive right to reproduce, modify and distribute such material as we see fit for any purpose in any form, media, or technology now known or later developed. You agree that we and our Affiliates may identify you as the author of any of your postings by name, email address or screen name as we see appropriate. You also permit any other user to access, display, and print such content for personal use. By submitting material to us, you are representing that such material does not violate or infringe any rights of any third party, including, but not limited to, copyright, trademark and other proprietary rights. If any third-party content is included in any materials that you submit, you must obtain permission from the content owner and attribute such content to the owner. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Notice of Copyright Infringement. </b>If you are an owner of intellectual property who believes your intellectual property has been improperly posted or distributed via this site, please notify us by sending an email to dmcanotice@meredith.com or by sending a notice by U.S. Mail to: John S. Zieser at Meredith Corporation, 1716 Locust Street, Des Moines, Iowa 50309. Please note that we may access and disclose your personally identifiable information in order to address any infringement claim. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b>Indemnity. </b>You agree to hold us and our affiliates, agents and licensors harmless from any claim that may arise from your use of any of our sites.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="third"></a>4. Third Party Services </b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">As a convenience to you, we may provide links to third-party websites. Those websites and the parties that control them are beyond our control. We make no representations as to the content, quality, suitability, functionality or legality of any sites to which we may provide links, and you hereby waive any claim you might have against us with respect to such sites and their operators. You may order services or merchandise through links on our sites from persons not affiliated with us. All matters concerning such merchandise or services, including, but not limited to, purchase terms, payment terms, warranties, guarantees, maintenance and delivery, are solely between you and the merchants with whom you chose to do business. We make no warranties or representations whatsoever with regard to any goods or services provided by those merchants.  You will not consider us - nor will we be deemed - a party to such transactions, whether or not we may have received some form of remuneration in connection with the transaction. We will not be liable for any costs or damages arising out of any transaction (whether directly or indirectly) between you and any other person or entity. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="disclaimer"></a>5. Disclaimer of Warranties </b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">YOU AGREE THAT USE OF THE SITES IS AT YOUR SOLE RISK. OUR SITES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. MEREDITH CORPORATION, ITS AFFILIATES, AGENTS AND LICENSORS CANNOT AND DO NOT WARRANT THE ACCURACY, COMPLETENESS, CURRENTNESS, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE OF THE INFORMATION, MATERIALS AND SERVICES AVAILABLE THROUGH OUR SITES. WE DO NOT GUARANTEE OUR SITES TO BE ERROR-FREE, SECURE, CONTINUOUSLY AVAILABLE OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. </font></p>
    <p><font face="Arial, Helvetica, sans-serif">YOU ALSO AGREE THAT IF YOU RELY ON ANY DATA OR INFORMATION OBTAINED THROUGH OUR SITES, YOU DO SO AT YOUR OWN RISK. YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE OR LOSS THAT RESULTS FROM YOUR USE OF ANY MATERIAL AND/OR DATA. </font></p>
    <p><font face="Arial, Helvetica, sans-serif">OUR SITES ARE PROVIDED WITH THE UNDERSTANDING THAT NEITHER MEREDITH CORPORATION NOR ITS USERS, WHILE SUCH USERS ARE PARTICIPATING IN THE SITES, ARE ENGAGED IN RENDERING LEGAL, MEDICAL, COUNSELING OR OTHER PROFESSIONAL SERVICES OR ADVICE. OUR SITES ARE NO SUBSTITUTE FOR PROFESSIONAL SERVICES OR ADVICE. </font></p>
    <p><font face="Arial, Helvetica, sans-serif">MEREDITH CORPORATION, ITS AFFILIATES, AGENTS, AND LICENSORS MAKE NO WARRANTY REGARDING ANY GOODS OR SERVICES REFERRED TO, ADVERTISED ON, OR OBTAINED THROUGH OUR SITES, OTHER THAN THOSE EXPRESS WARRANTIES MEREDITH  CORPORATION ITSELF SPECIFICALLY MAKES ON ANY MEREDITH CORPORATION ORDER FORM. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="limitation"></a>6. Limitation of Liability </b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">UNDER NO CIRCUMSTANCES WILL MEREDITH CORPORATION OR ITS AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DAMAGES ARISING OUT OF YOUR USE OF ANY OF OUR SITES, INCLUDING, WITHOUT LIMITATION, LIABILITY FOR CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, OR SIMILAR DAMAGES, EVEN IF WE ARE ADVISED BEFOREHAND OF THE POSSIBILITY OF SUCH DAMAGES. YOU AGREE THAT THE LIABILITY OF MEREDITH CORPORATION, ITS AFFILIATES, AGENTS AND LICENSORS, IF ANY, ARISING OUT OF ANY KIND OF LEGAL CLAIM IN ANY WAY CONNECTED TO ANY OF OUR SITES WILL NOT EXCEED THE AMOUNT YOU PAID TO US TO USE THE SITES. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN CATEGORIES OF DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, THE LIABILITY OF MEREDITH CORPORATION, ITS AFFILIATES, AGENTS AND LICENSORS IS LIMITED TO THE FULLEST EXTENT PERMITTED BY SUCH STATE LAW. </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="discontinuance"></a>7. Discontinuance, Modification & Restrictions</b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">We may discontinue, change, suspend, or restrict access to any of our sites or any portion of our sites at any time without liability to you or any third party.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="applicable"></a>8. Applicable Law & Exclusive Jurisdiction </b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">This site is controlled and operated by Meredith Corporation from the state of Iowa in the United States of America. Those who choose to access our site from other locations do so on their own initiative and are responsible for compliance with applicable local laws. This Visitor Agreement constitutes an agreement made in, and to be construed in accordance with the laws of, the State of Iowa without regard to its conflict of law provisions. By using this site, you consent to the exclusive jurisdiction of the state and federal courts in Polk County, Iowa, in all disputes arising out of or relating to this agreement or any of our sites. 
      </font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="dispute"></a>9. 
        Dispute Resolution </b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">You agree not take any legal action against us that relates to or arises out of any of our websites without first (a) sending us, via registered mail or national overnight courier service, a detailed written description of the facts and law out of which your claim arises; and (b) negotiating with us, in good faith, for not less 30 days, toward resolution of the dispute. All correspondence concerning such dispute must be sent to dispute at meredith.com, or such other designee as Meredith may identify from time to time.</font></p>
    <p><font face="Arial, Helvetica, sans-serif"><b><a name="misc"></a>10. Miscellaneous</b></font></p>
    <p><font face="Arial, Helvetica, sans-serif">In the event that any provision of this Visitor Agreement conflicts with the law under which this Visitor Agreement is to be construed or if any provision is held invalid by a court with jurisdiction over the parties to the Visitor Agreement, such provision will be restated to reflect as nearly as possible the original intentions of the parties in accordance with applicable law, and the remainder of this Visitor Agreement will remain in full force and effect. If either party fails to insist upon or enforce strict performance by the other party of any provision of the Visitor Agreement, or to exercise any right under the Visitor Agreement, such a failure will not be construed as a waiver or relinquishment to any extent of such party's right to assert or rely upon any such provision or right in that or any other instance.</font></p>
    <p><font face="Arial, Helvetica, sans-serif">This Visitor Agreement constitutes the entire understanding between the parties as to the subject matter hereof, and supersedes all prior agreements and understandings relating to such subject matter. </font></p>
    <p><font face="Arial, Helvetica, sans-serif">Copyright</font></p>
    <p><font face="Arial, Helvetica, sans-serif">Contents on this site are copyright 1996-2011 by Meredith Corporation or its affiliates or licensors. Unauthorized distribution or reproduction is forbidden. If you have questions or wish to obtain more information from or about Meredith Corporation, please visit <a href="http://www.meredith.com">meredith.com.</a></font></p>
  </div>
</div>
