default:
  has_layout:     true
  layout:         layout_bare
  javascripts:    [jquery-1.6.2.min.js, jquery-ui-1.8.14.custom.min.js, -betterrecipes.js, -s_code_betterrecipesH.js]
  stylesheets:    [ui-darkness/jquery-ui-1.8.14.custom.css, myrecipebox_popup.css, -betterrecipes.css]

indexSuccess:
  stylesheets:    [betterrecipes.css, ui-darkness/jquery-ui-1.8.14.custom.css]
  javascripts:    [jquery-1.6.2.min.js, betterrecipes.js, s_code_betterrecipesH.js]
  layout:         layout