all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=<?= ini_get("mysql.default_host") ?>;port=<?= ini_get("mysql.default_port") ?>;dbname=betterrecipes'
      username: '<?= ini_get("mysql.default_user") ?>'
      password: '<?= ini_get("mysql.default_password") ?>'
      encoding: utf8
      persistent:
        value:  true
      attributes:
        quote_identifier: true
        use_native_enum: true
        validate: all
        idxname_format: %s_idx
        seqname_format: %s_seq
        tblname_format: %s
        DEFAULT_TABLE_TYPE: InnoDB
        DEFAULT_TABLE_CHARSET: utf8
        DEFAULT_TABLE_COLLATE: utf8_general_ci