# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

detailSuccess:
  javascripts:    [jquery-1.6.2.min.js, jquery.jlembed.js, writeCapture.js, jquery.writeCapture.js, adtagRefresh.js, betterrecipes.js]