<div class="article fullwidth">
  <p class="title">
    Better Recipes
  </p>
  <p class="title">
    Daily Dish Blog Giveaway
  </p>
  <p class="title">
    Official Rules 
  </p>
  <p class="mt10">Void outside the 50 United States, District of Columbia and where prohibited. Do not proceed to enter if you are not at least 21 years of age and a legal resident of, and located within, one of the 50 United States, or the District of Columbia, at the time of entry.</p>
  <p class="mt10">NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE WILL NOT INCREASE YOUR CHANCES OF WINNING.</p>
  <p class="mt10">The Better Recipes Blog Giveaway begins 5:00 a.m. Central Time ("C.T.") on August 22, 2011, and ends at 11:59 p.m. C.T. on October 16, 2011. There are eight (8) weekly entry periods (each an "Entry Period"), as follows:</p>
  <ul>
  	<li class="mt10">Week 1 Entry Period: Begins 5:00 a.m. C.T. on August 22, 2011 and ends at 11:59 p.m. C.T. on August 28, 2011.</li>
    <li class="mt10">Week 2 Entry Period: Begins 5:00 a.m. C.T. on August 29, 2011 and ends at 11:59 p.m. C.T. on September 4, 2011.</li>
    <li class="mt10">Week 3 Entry Period: Begins 5:00 a.m. C.T. on September 5, 2011 and ends at 11:59 p.m. C.T. on September 11, 2011.</li>
    <li class="mt10">Week 4 Entry Period: Begins 5:00 a.m. C.T. on September 12, 2011 and ends at 11:59 p.m. C.T. on September 18, 2011.</li>
    <li class="mt10">Week 5 Entry Period: Begins 5:00 a.m. C.T. on September 19, 2011 and ends at 11:59 p.m. C.T. on September 25, 2011.</li>
    <li class="mt10">Week 6 Entry Period: Begins 5:00 a.m. C.T. on September 26, 2011 and ends at 11:59 p.m. C.T. on October 2, 2011.</li>
    <li class="mt10">Week 7 Entry Period: Begins 5:00 a.m. C.T. on October 3, 2011 and ends at 11:59 p.m. C.T. on October 9, 2011.</li>
    <li class="mt10">Week 8 Entry Period: Begins 5:00 a.m. C.T. on October 10, 2011 and ends at 11:59 p.m. C.T. on October 16, 2011.</li>
  </ul>
  <p class="mt10">ENTRY: To enter, go to The Daily Dish at <a href="http://www.betterrecipes.com/bloggiveaway">http://www.betterrecipes.com/bloggiveaway</a> and provide your name and email address. Then, post a brief comment in the comment section of the featured weekly blog, stating that you have completed the weekly task set forth below.</p>
  <ul>
  	<li class="mt10">Week 1: Between 5:00 a.m. C.T. on August 22, 2011 and 11:59 p.m. C.T. on August 28, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 2: Between 5:00 a.m. C.T. on August 29, 2011 and 11:59 p.m. C.T. on September 4, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 3: Between 5:00 a.m. C.T. on September 5, 2011 and 11:59 p.m. C.T. on September 11, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 4: Between 5:00 a.m. C.T. on September 12, 2011 and 11:59 p.m. C.T. on September 18, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 5: Between 5:00 a.m. C.T. on September 19, 2011 and 11:59 p.m. C.T. on September 25, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 6: Between 5:00 a.m. C.T. on September 26, 2011 and 11:59 p.m. C.T. on October 2, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 7: Between 5:00 a.m. C.T. on October 3, 2011 and 11:59 p.m. C.T. on October 9, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
    <li class="mt10">Week 8: Between 5:00 a.m. C.T. on October 10, 2011 and 11:59 p.m. C.T. on October 16, 2011, post a brief comment on the weekly blog at betterrecipes.com/bloggiveaway. Limit: One (1) Weekly entry per person with a valid email address.</li>
  </ul>
  <p class="mt10">No group entries. Any attempt to obtain more than the stated number of entries by using multiple/different email addresses, identities, registrations, logins, or any other methods may result in disqualification by Sponsor, in its sole discretion.</p>
  <p class="mt10">ELIGIBILITY: Legal residents of the 50 United States, and the District of Columbia, 21 years of age or older are eligible to enter, except employees of Sponsor, and any other organizations affiliated with the sponsorship, fulfillment, administration, prize support, advertisement or promotion of the Sweepstakes and/or their respective agents, affiliates, subsidiaries and members of their immediate families or persons residing at the same address. "Immediate family members" shall mean parents, step-parents, children, step-children, siblings, step-siblings, or spouses. "Household members" shall mean people who share the same residence at least three months a year.</p>
  <p class="mt10">WINNER SELECTION AND PRIZING: On or about October 24, 2011, Sponsor will conduct a random drawing from among all eligible entries received for each weekly Entry Period.</p>
  <ul>
  	<li class="mt10">One (1) Week 1 winner will receive a Chicken Package (vertical roasting rack, four (4) plates, four (4) napkins, serving platter, cheese platter, and thermometer), retail value ("RV") $55.</li>
    <li class="mt10">One (1) Week 2 winner will receive a Watermelon Package (red cutting board, four (4) watermelon bowls, watermelon platter, dish towel, pot holder, melon baller, watermelon knife, and measuring spoons), RV $75.</li>
    <li class="mt10">One (1) Week 3 winner will receive an Ice Cream Package (Cuisinart Ice Cream Maker, ice cream scoop, two (2) ice cream bowls, and two (2) ice cream spoons), RV $80.</li>
    <li class="mt10">One (1) Week 4 winner will receive an Italian Package (four (4) pasta bowls, an Italian apron, olive oil carafe, garlic holder, and a pasta cookbook), RV $70.</li>
    <li class="mt10">One (1) Week 5 winner will receive a Martini Package (martini shaker, jigger, four (4) martini glasses, Marimekko dish towels, 101 Martinis cookbook, and a cocktail food cookbook), RV $115.</li>
    <li class="mt10">One (1) Week 6 winner will receive a Paris Package (four (4) Paris dessert plates, dish towel, Eifel tower candle holder, and Barefoot in Paris cookbook), RV $80.</li>
    <li class="mt10">One (1) Week 7 winner will receive a Wok Package (Crate and Barrel Wok Set, Wok cookbook, three (3) small sauce bowls), RV $75.</li>
    <li class="mt10">One (1) Week 8 winner will receive a Moroccan Package (Tagine, Marrakech dishtowel, and a Tagine cookbook), RV $45.</li>
  </ul>
  <p class="mt10">One prize per person.  Winners will be notified and prizes will be delivered approximately thirty (30) days from date of winner verification. Sponsor reserves the right to substitute a prize (or portions thereof) of equal or greater value if prize (or portions thereof) cannot be awarded as described. Sponsor will determine all elements of prizing in its sole discretion. Prize may not be assigned, transferred, or changed, except at Sponsor's sole discretion. Prize is awarded "as is" with no warranty or guarantee express or implied by Sponsor. Sponsor disclaims all and any liability for the actual provision, quality or nature of any third-party product or service accepted by the winners. The awarding of any prize is contingent upon full compliance with these Official Rules. Entrants agree to be bound by Official Rules and agree that if any winner fails to provide proof of identity, refuses to provide documentation, is found to have violated Official Rules, or otherwise does not meet eligibility criteria, prize will be forfeited and awarded to an alternate winner in a random drawing. Entrants understand that Sponsor is not liable for injuries, losses, or damages of any kind arising from participation in this promotion and acceptance, possession, and use of prize. Sponsor is not responsible for any typographical or other error in the printing of the offer, administration of the sweepstakes or in the announcement of the prize. Decisions of Sponsor are final and binding in all respects.</p>
  <p class="mt10">ODDS of winning depend upon the number of eligible entries received.</p>
  <p class="mt10">PRIVACY: By entering the sweepstakes, you consent to the use of your personal information (including your name, mailing address, and email address) by Sponsor and its authorized agents for the purposes of administering the sweepstakes and fulfilling the prizes to the winners. At the time of entry, you may also have the opportunity to request to receive information and offers from Sponsor. Such requests are optional and will not affect your chances of winning. For more information about how Sponsor uses the information you provide, see Sponsor's privacy policy at <a href="http://www.betterrecipes.com.">www.betterrecipes.com.</a></p>
  <p class="mt10">DISPUTE RESOLUTION: Except where prohibited, by participating Sweepstakes entrants agree that: All issues and questions concerning the construction, validity, interpretation and enforceability of these Official Rules, or the rights and obligations of participant(s) and Sponsor and its agents shall be governed by and construed exclusively in accordance with the laws of the State of New York without giving effect to any principles of conflicts of law of any jurisdiction. Entrant agrees that any action at law or in equity arising out of or relating to this Sweepstakes, or awarding of the prizes, shall be filed only in the state or federal courts located in the State of New York and entrant hereby consents and submits to the personal jurisdiction of such courts for the purposes of litigating any such action. Except where prohibited, by participating in this Sweepstakes, entrant agrees that: (a) any and all disputes, claims, and causes of action arising out of or connected with this Sweepstakes, or awarding of the prizes, shall be resolved individually, without resort to any form of class action; and (b) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with participating in this Sweepstakes but in no event attorneys' fees; and (c) under no circumstances will any participant be permitted to obtain awards for and hereby waives all rights to claim punitive, incidental and consequential damages and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased. Some jurisdictions do not allow the limitations or exclusion of liability for incidental or consequential damages, so the above may not apply to you.</p>
  <p class="mt10">OTHER: Sponsor assumes no responsibility for entries it is unable to process due to network, hardware or other technical failures; or any other reason, or incomplete, damaged, misdirected, or lost entries. Sponsor reserves the right, in its sole discretion to disqualify any person tampering with the entry process, the operation of the web site or otherwise in violation of these Official Rules. Sponsor further reserves the right, in its sole discretion, to cancel, terminate or modify this promotion if not capable of completion as planned, including infection by computer virus, technical corruption, non-authorized human intervention, or any other causes beyond the control of the Sponsor which corrupt or affect the administration, security, fairness, or integrity of the sweepstakes. Sponsor reserves the right in its sole discretion to disqualify any individual it believes has tampered with the entry process, and/or cancel, terminate, modify or suspend the sweepstakes. In the event of cancellation, Sponsor reserves the right to select winners from among all eligible entries received prior to date of cancellation. The use of automated entry systems or any other conduct that impedes the integrity of the sweepstakes is prohibited. In the event of a dispute regarding online entry, entry will be deemed made by the holder of an established e-mail account associated with the entry.</p>
  <p class="mt10">GENERAL: Except where prohibited by law: (i) entry constitutes permission to use winners' entry, name, hometown, voice, likeness, photograph and any statements regarding this sweepstakes for editorial, public relations, promotional and advertising purposes on behalf of Sponsor without compensation; (ii) potential winners may be required to complete and return an Affidavit of Eligibility and Release of Liability/Publicity within ten (10) days of notification or an alternate winner may be selected by random drawing. If winner notification is returned as undeliverable, an alternate winner may be selected by random drawing. By participating and winning a prize, winners release Sponsor, its parents, affiliates, subsidiaries and agencies and their respective directors, officers, employees and agents from any and all liability with respect to the prize won and participation in the sweepstakes. Subject to all U. S. federal, state and local laws and regulations. Void where prohibited. Taxes on prizes are the sole responsibility of the winners. For winners' list, available after October 31, 2011, send a separate, self-addressed, stamped envelope to Winner list, Better Recipes Daily Dish Blog, 1716 Locust St., LN-102, Des Moines, IA 50309-3023.</p>
</div>