# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

detailSuccess:
  stylesheets:    [-/css/ui-darkness/jquery-ui-1.8.14.custom.css: { raw_name: true }, /css/smoothness/jquery-ui-1.8.18.custom.css: { raw_name: true }]